k9:
  fqdn: k9.midorlo.com
  security:
    strategy: MODE_INHERITABLETHREADLOCAL
    key: MzgxNjBhNzIxMzM0MjFhMGE1M2Q1YTY4NWQ2MTcyODhjYTc3MTI1MzkzZDM5NWFmODFmMTYxOTJlNzIxMGM4NWQ2MjI0NTIyODM4ZTQxNDUzMTE0NzhjN2E0NzE2M2MxMzg0MjhhNWRkYjA4M2FiZjY0OWYxYWI3N2UwNTlhNGE
    issuer: k9.midorlo.de
    validityMs: 1800
    extendedValidityMs: 3600

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      pool-name: k9
      password: k9
      username: k9
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=security
    password: dev
    username: dev
#    generate-ddl: off
#  sql:
#    init:
#      platform: postgres
#      mode: always
#  output:
#    ansi:
#      enabled: always