security:
  strategy: MODE_INHERITABLETHREADLOCAL
  key: MzgxNjBhNzIxMzM0MjFhMGE1M2Q1YTY4NWQ2MTcyODhjYTc3MTI1MzkzZDM5NWFmODFmMTYxOTJlNzIxMGM4NWQ2MjI0NTIyODM4ZTQxNDUzMTE0NzhjN2E0NzE2M2MxMzg0MjhhNWRkYjA4M2FiZjY0OWYxYWI3N2UwNTlhNGE
  issuer: k9.midorlo.de
  validityMs: 1800
  extendedValidityMs: 3600
